version: "3.7"
services:
    
  output_file:
    build:
      context: './apache/'
    networks:
      - backend
    ports:
      - "8000:80"  
    volumes:
      - '.:/var/www/html/'
    container_name: output_file
    
  output_file_mailcatcher:
    image: schickling/mailcatcher
    container_name: output_file_mailcatcher
    ports:
    - "8001:1080"
    - "1025:1025"
    networks:
    - backend
    
networks:
  backend:
    driver: bridge

